### ISSUE TITLE
Missing cloudfoundry_app is'nt detected in the plan phase

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#163]
Missing cloudfoundry_app is'nt detected in the plan phase, and thus not recreated when missing

Steps to reproduce:
1- `terraform apply` on https://github.com/gberche-orange/terraform-cloudfoundry-demo/blob/6adc711ba9de5277db75c60ff9909ec295b76629/provider_cloudfoundry.tf#L1-L70
2- delete the app from cf: `cf d -f dora`
3- `terraform apply`

expected behavior: should display the provisionning of the app

observed behavior:

```
/usr/sbin/terraform apply
data.cloudfoundry_service.elephantsql: Refreshing state...
data.cloudfoundry_domain.default_domain: Refreshing state...
data.cloudfoundry_org.my_org: Refreshing state...
cloudfoundry_space.demo-basel: Refreshing state... (ID: 40a34a10-810e-41d6-a80a-bfb33a6115c9)
cloudfoundry_service_instance.my_mysql: Refreshing state... (ID: 6f423977-f3a4-411f-9122-d51e24dfb059)
cloudfoundry_route.dora-tf-demo: Refreshing state... (ID: d6ab3f0c-2f0a-4b4e-80de-328738cface6)
cloudfoundry_app.dora: Refreshing state... (ID: c549970b-eb4f-4413-9068-eed5a7e1ce2e)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

workaround (to have the missing app be recreated): manually remove the app from the tfstate

```
terraform state rm cloudfoundry_app.dora
terraform apply
```

**Comment by janosbinder** [comment]
Hi Guillaume,

IMO this is the expected behavior. No changes happened in the tf config file and therefore it corresponds to the tfstate file. Therefore terraform does not even make a call using the provider. If you want to retrigger, or simulate to see what happens if the app missing, there are two ways:

1, `terraform taint cloudfoundry_app.dora` before the second apply
2, In your tf file before the second run, add some change (e.g. add memory to `resource "cloudfoundry_app" "dora")

Let me please know, what do you see.

**Comment by gberche-orange** [comment]
apologies, my test was apparently running a old version of the provider, not 0.9.9 as I though and thus not including #133

Sorry for the associated noise.
