### ISSUE TITLE
Deletion of Service Instances

### ISSUE THREAD

**Issue by samedguener** [mevansam/terraform-provider-cf#36]
Dear contributors,

the deletion of a service instance having service binding, service keys etc. fails. Terraform outputs that service instances with bindings, service key etc. can not be deleted. In fact after deleting all bindings etc., one is able to delete the service instance.

I investigated and saw that the [deletion request to the cf api](https://apidocs.cloudfoundry.org/280/service_instances/delete_a_service_instance.html) accepts the parameter `recursive`, which leads to `Will delete service bindings, service keys, and routes associated with the service instance.`

I propose that we shall add an additional flag in the resource `cf_service_instance`, where users can choose between trying to delete the service instance or delete the service instance by deleting all dependencies.

I will create a PR for this issue/feature request asap.

I'd like to hear your opinion about that.

Best,
Samed

**Comment by samedguener** [comment]
Proposed solution in [#37](https://github.com/mevansam/terraform-provider-cf/pull/37).


Best,
Samed

**Comment by gberche-orange** [comment]
Thanks @samedguener for this issue and the associated contribution. 

Can you please clarify the use-cases into which a user would have removed as a service-instance from TF configs (i.e. asking TF to remove the service-instance resource), but not the associated service bindings, and service-keys ? Have you observed leaks in some other resources such as `cf_app` or `cf_service_key` ?

IMO, if the related service bindings and service-keys resources were not created/managed by the TF state, then the terraform-provider-cf should probably not act on these resources.

**Comment by chrismathias** [comment]
@gberche-orange some insight into our use case as @samedguener  is out of office.

We are deploying a service broker (cf_service_broker and associated cf_app) and create service instances within the same space for binding to additional applications. 
We have an explicitly declared dependency between the cf_app of the service broker and the created service instances. Whenever there is a change in the cf_app of the service broker, the service instances need to be deleted and re-created. 

When running terraform we observe that terraform presently does not unbind the service instances from the apps and hence fails to delete. Instead we get a message indicating we need to manually unbind the instances and re-run terraform (which actually solves the issue). However, we would like to get rid of this manual step. 

Reading over the documentation it occurs to me that our problem may actually occur because we declare the service binding within cf_app and not as a separate resource cf_service_binding. However, as the service bindings are required during startup, I don't see how we can use the cf_service_binding resource. The service keys are all taken care of by terraform as this is a separate resource.

Therefore @samedguener implemented #37 for us to rid us of the manual steps. If there is another way to do this your insight would be very welcome.

**Comment by gberche-orange** [comment]
> We have an explicitly declared dependency between the cf_app of the service broker and the created service instances. Whenever there is a change in the cf_app of the service broker, the service instances need to be deleted and re-created.

Is this systematic dependency really required ? I guess the cf app updates does not always requires service binding/instance recreation (otherwise the service broker catalog and binding response is quite instable, and users of the service will have a hard time using it).

It seems unusual in production environment to delete services instances without consent from developers that instanciated them.

Is it a use case occurring during service broker development (e.g. in which service instances are generated from automated smoke tests) ?

> If there is another way to do this your insight would be very welcome.

You might want to try to register a [destroy-time provisioner](https://www.terraform.io/docs/provisioners/index.html#destroy-time-provisioners) script associated with the service broker resource that would related delete service instances not managed within the TFstate.

Another alternative would be to use a orchestration tool on top of TF to sequence deletion of the service instances.

**Comment by chrismathias** [comment]
Hi,
The way our platform is built, we construct a service broker which provides URLs that are then consumed by other apps in the same space. Our complete platform is deployed through terraform (no manual deployment parts in the same space), which means there are no manually created service instances or bindings either. Users of our platform instantiate service instances of the service broker in their own space which is not under our control, and that is not really an issue.

Besides, our problem is independent of this construction. Even if we just use an external service such as application log, the service instance cannot be deleted if we taint it since the bindings are still there; and I am a bit reluctant to add scripts to every service instance resource we deploy - from my point of view, this should be taken care of by terraform; that's why I would like to have this in terraform as optional configuration. If I feel that the service broker can be safely unbound I would add the additional parameter that @samedguener  has proposed in his PR to the service instance. We would have this additional option without breaking anything that is not intended.

I guess it's a chicken-egg problem, as the bindings are defined in the app and so terraform would need to unbind first, delete, and rebind.

**Comment by gberche-orange** [comment]
> we construct a service broker which provides URLs that are then consumed by other apps in the same space. 

For this particular use-case of a service broker development cycle with volatile test service instances and bindings owned by the service broker development team, the provisionner scripts in the **service broker resource** (not service instance) TF config might address this specific need. They can be made optional when the broker is deployed in production and its upgrade will not require service instance deletion.

> Users of our platform instantiate service instances of the service broker in their own space which is not under our control, [...]
> I guess it's a chicken-egg problem, as the bindings are defined in the app and so terraform would need to unbind first, delete, and rebind.

As bindings are defined in the app's space, they usually fall under the responsibility of the consumer app team. This may translates in particular to the credentials used by the terraform provider to deploy the service brokers not systematically be sufficient to act on the app's service bindings.

So I'm still uncomfortable for the [service_instance](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/service_instance.html.markdown) to have a recursive delete flag that would conflict with the [cf_app.service_binding](https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/app.html.markdown#service-bindings) resource desired state, and potentially act on resources not managed within the TF state.

Maybe @mevansam @psycofdj or @ArthurHlt have a different opinion they'd like to share. Alternatively, this can be discussed interactively in one of our weekly status calls.

**Comment by chrismathias** [comment]
To lead this discussion to a close. Even though I think that whoever enables this flag should be aware of the risks and it is only a further capability, I understand that at the moment this isn't something that you want to tackle. So I would propose we put this issue in the freezer for now and maybe revisit at a later point in time.

**Comment by gberche-orange** [comment]
thanks @chrismathias for the update. I'm therefore closing this issue and the related PR. Feel feel to reopen both of them when we need to unfreeze the discussion.
