### ISSUE TITLE
rename provider from cf to cloudfoundry

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#44]
This is a split of #38 

To allow a tfstate to include both https://github.com/mevansam/terraform-provider-cf and https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/ , the latter will be renamed to something like `legacy_cloudfoundry`, see https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/issues/33

**Comment by gberche-orange** [comment]
closed by #85 

Migration steps for mevansam/terraform-provider-cf releases <= 0.9.8 are documented into https://github.com/mevansam/terraform-provider-cf/pull/85#issuecomment-395998798

**Comment by tgpo-sap** [comment]
@gberche-orange Following the links from your first post, the reason to rename `cf_` to `cloudfoundry_` is to address a comment from Terraform team, and this is more of aesthetic/styling/convention/standard purpose, rather than avoiding any potential functional conflicts. May I know if my statement is correct? Thank you.

**Comment by gberche-orange** [comment]
@tgpo-sap yes you're right, hashicorp's request was to make the provider naming explicit and match naming conventions that aims to avoid ambiguous acronyms
