### ISSUE TITLE
at least run `goimports` on the code + prune unused vendor libs

### ISSUE THREAD

**Issue by gberche-orange** [mevansam/terraform-provider-cf#48]
This is a split of #38 

- [x] Please at least run goimports on the code (many editors can do this automatically, vim-go, vscode, etc.), optionally you could also use golint or even gometalinter to help find additional issues. Passing gometalinter is unnecessary for CI, but it’s a good tool when developing, below is a sampling of other issues I found with the tools. 
- [x] The vendor dir seems to include some unused stuff and the vendor.json seems to be out of sync with it, but I may be missing something, probably worth taking a pass at your dependencies (especially once `goimports` cleans up your imports) and ensure they are all necessary.

**Comment by ArthurHlt** [comment]
Actually, https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/import_cf_service_instance_test.go#L38-L66 is a copy of https://github.com/mevansam/terraform-provider-cf/blob/master/cloudfoundry/resource_cf_service_instance_test.go#L135-L163 

It seems that tools didn't find really well the issue here. There is no return before the loop but have a fallback return inside the loop which imply only one loop.

I'm not sure what you were trying to do on this part @mevansam, could you give some informations ? I will fix them

**Comment by mevansam** [comment]
There is a bug in this logic. It is supposed to check that one or more of the given instance names have been deleted, exits after validating the first. The actual logic should be.

```
		for _, n := range names {

			session.Log.DebugMessage("checking ServiceInstance is Destroyed %s", n)

			if _, err := session.ServiceManager().FindServiceInstance(n, rs.Primary.ID); err != nil {
				switch err.(type) {
				case *errors.ModelNotFoundError:
					**continue**

				default:
					break
				}
			}
			return fmt.Errorf("service instance with name '%s' still exists in cloud foundry", n)
		}
```

**Comment by gberche-orange** [comment]
@ArthurHlt I also bundled the unused vendor pruning aspect into this issue.

**Comment by ArthurHlt** [comment]
About vendors libs:

Running `govendor list +unused` make me found 2 unused deps:

```
github.com/hashicorp/terraform/helper/experiment
github.com/hashicorp/terraform/helper/shadow
```

**Comment by ArthurHlt** [comment]
I've fixed the import test check with the `continu` fix provided by @mevansam.

I considered this 2 things as fixed. 
Reopen if vendors libs have still unused libs
